

export const ActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    SET_CATEGORY: "SET_CATEGORY",
    ADD_CART: "ADD_CART",
    REMOVE_CART: "REMOVE_CART",
    ADD_FAV: "ADD_FAV",
    REMOVE_FAV: "REMOVE_FAV",
    SET_USER: "SET_USER",
    RESET_USER: "RESET_USER"
}